DATE_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
DATE_FORMAT = '%Y-%m-%d'
SQL_DATE_FORMAT = 'YYYY-MM-DD'
SQL_DATE_FORMAT_FULL = 'YYYY-MM-DD HH24:MI:SS'
EMPTY_STRING = ""
STATUS_DISABLE = 'Disable'
STATUS_UP = 'Up'
STATUS_DOWN = 'Down'
STATUS_UNKNOW = 'Unknow'
STATUS_ERROR = 'Error'
STATUS_NA = 'N/A'
DEFAULT_TIME_OUT = 500

# SNMP
MODE_PUBLIC = 'public'
SNMP_V1_MP_MODEL = 0
SNMP_V2C_MP_MODEL = 1
MODE_PRIVATE = 'private'
SNMP_MIB = 'SNMPv2-MIB'
TRANSPORT_PORT = 161
IP_REGEX = r'^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'

#ref: https://www.rfc-editor.org/rfc/rfc1907#section-2.1
OID_SYSTEM_DESCRIPTION = 'sysDescr'
OID_SYSTEM_UP_TIME = 'sysUpTime'
OID_SYSTEM_CONTACT = 'sysContact'
OID_SYSTEM_LOCATION = 'sysLocation'
OID_SYSTEM_NAME = 'sysName'
OID_SYSTEM_SERVICE = 'sysServices'

OID_TRAFFIC_INCOMING = "1.3.6.1.2.1.2.2.1.10"
OID_TRAFFIC_OUTGOING = "1.3.6.1.2.1.2.2.1.16"

SUPPORT_ODI = [
    OID_SYSTEM_DESCRIPTION,
    OID_SYSTEM_UP_TIME,
    OID_SYSTEM_CONTACT,
    OID_SYSTEM_NAME,
    OID_SYSTEM_SERVICE,
]